config/routes.rb
Rails.application.routes.draw do

  get 'play/index'
  get 'play/game'
  get 'play/start'
  get 'play/round'
  get 'play/question'
  get 'play/answer'

  resources :questions
  resources :rounds 
  resources :games

  

  root 'play#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :rounds
	accepts_nested_attributes_for :rounds, allow_destroy: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :round
end

app/models/round.rb
class Round < ActiveRecord::Base
	belongs_to :game 
	has_many :questions
	accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index 
		@games = Game.all 
	end 

	def show 
		@game = Game.find(params[:id])
	end 

	def new 
		@game = Game.new 
	end 

	def edit 
		@game = Game.find(params[:id])
	end 

	def create 
		@game = Game.new(game_params)
		if @game.save 
			redirect_to @game 
		else 
			render 'new'
		end 
	end 

	def update 
		@game = Game.find(params[:id])

		if @game.update(game_params)
			redirect_to @game 
		else 
			render 'edit' 
		end
	end 

	def destroy
		@game = Game.find(params[:id])
		@game.destroy

		redirect_to play_game_path
	end 

	private 
		def game_params 
			params.require(:game).permit(:name, :round_ids => [])
		end



end

app/controllers/play_controller.rb
class PlayController < ApplicationController


	def game 
		@games = Game.all 
	end 

	def round
		@game = Game.find(params[:game])
		@rounds = @game.rounds 
	end

	def start 
		@game = Game.find(params[:game])
	end

	def question 
		@game = Game.find(params[:game])
		@round = Round.find(params[:round])
		@counter = params[:counter]
		@question = @round.questions[@counter.to_i()]
		#figure out question -> next 
	end

	def answer
		@game = Game.find(params[:game])
		@round = Round.find(params[:round])
		@counter = params[:counter]
		@question = Question.find(params[:question])
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	
	def index 
		@questions = Question.all 
	end 

	def show 
		@question = Question.find(params[:id])
	end

	def new
		@question = Question.new
	end

	def edit
		@question = Question.find(params[:id])
	end

	def create 
		@question = Question.new(question_params)

		@question.save 
		redirect_to @question
	end 

	def update
			@question = Question.find(params[:id])

		if @question.update(question_params)
			redirect_to @question 
		else 
			render 'edit' 
		end
	end

	# This is maybe not good.
	def destroy
		@question = Question.find(params[:id])
		@question.destroy

		redirect_to questions_path
	end

	private 
		def question_params 
			params.require(:question). permit(:questiontext, :answertext, :partialanswer, :pointval, :difficulty, :partialpoints, :isanswered, :notes)
		end 
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

	def index
		@rounds = Round.all
		#@round.questions.build
	end

	def show
		@round = Round.find(params[:id])
	end

	def new
		@round = Round.new
		@round.questions.build
		@questions = Question.all 
		@question = Question.new 
	end

	def edit 
		@round = Round.find(params[:id])
	end

	def create
		@round = Round.new(round_params)
		if @round.save 
			redirect_to @round
		else 
			render 'new'
		end 

	end

	def update
		@round = Round.find(params[:id])

		if @round.update(round_params)
			redirect_to @round
		else 
			render 'edit' 
		end
	end

	def destroy
		@round = Round.find(params[:id])
		@round.destroy

		redirect_to rounds_path
	end

	private
		def round_params
			params.require(:round).permit(:title, questions_attributes: [:questiontext, :answertext, :partialanswer, :pointval, :difficulty, :partialpoints, :notes], :question_ids => [])
		end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %> 

	<p> 
		<div class = "text">
			<%= f.label :name %><br>
		</div>
		<%= f.text_area :name %> 
	</p>

	<p> 
		<div class = "text">
			<label>Rounds in Game:</label>
					<!-- //using categories = game
					//concern = round -->
					
				
					<br><%= hidden_field_tag "game[game_ids][]", nil %>
					<% Round.all.sort_by{|round| round.title}.each do |round| %> 				
						<%= check_box_tag "game[round_ids][]", round.id, 
						@game.rounds.include?(round), id: dom_id(round)%>
						<%= label_tag dom_id(round), round.title%></br>


					<% end %> 
					

				<br/>
		</div>
	</p>
<%= f.submit class: "btn btn-success btn-sm" %>

<% end %> 
<br>
<%= link_to 'Return to Game List', play_game_path, class: 'btn btn-primary btn-sm'  %>

app/views/games/edit.html.erb
<div class = "page">
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center><h2>Edit Game</h2></center>
	</div> 

	<%= render 'form' %> 

</div>

app/views/games/new.html.erb
<div class = "page">
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center><h2>New Game</h2></center>
	</div> 

	<%= render 'form' %>

</div>

app/views/games/show.html.erb
<div class="page">

<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
<div class="heading">
	<center><%= @game.name %><center>
</div>

<!-- Navigation Bar -->
<center>
	<p>
		<%= link_to play_game_path, class: 'btn btn-nav' do %>
			<i class="glyphicon glyphicon-circle-arrow-up"></i> Games
		<% end %>

		<%= link_to play_index_path, class: 'btn btn-gray' do %>
			<i class="glyphicon glyphicon-align-justify"></i> Main Menu
		<% end %>
	</p>
</center>

<table class="table table-hover">
	<thead bgcolor="#6bbeff">
		<tr>
			<th>No.</th>
			<th>Round ID</th>
			<th>Round Title</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<% i = 1 %>
			<% @game.rounds.each do |rnd| %>
					<td> <%= i %> </td>
					<% i = i.to_i() + 1 %>
					<td> <%= rnd.id %> </td>
					<td> <%= link_to rnd.title, rnd %> </td>
					<td> <%= link_to edit_round_path(rnd), class: 'btn btn-gray btn-xs' do %>
					<i class="glyphicon glyphicon-pencil"></i> Edit
					<% end %>
					</td>
		</tr>
		<% end %>
	</tbody>
</table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trivia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/play/_head.html.erb
<head> 


</head>

app/views/play/answer.html.erb
<div id="title">
<%= image_tag("TAStars.jpg", :alt => "Banner") %> <%= @round.title%>
</div>


			<div class="sidebar left">
			
				<% if @counter == "0" %> 
					<h1><%= link_to image_tag("<_arrow.png", :alt => "Banner"), {:controller => "play", :action => "round", :game => @game.id} %></h1>

				<% else %> 
					<h1><%= link_to image_tag("<_arrow.png", :alt => "Banner"), {:controller => "play", :action => "question", :game => @game.id, :round => @round.id, :counter => (@counter.to_i() - 1)} %></h1>

				<% end %>

			</div>


			<div  class="sidebar right">
			
					<% if @counter == "6" %> 
						<h1><%= link_to image_tag(">_arrow.png", :alt => "Banner"), {:controller => "play", :action => "round", :game => @game.id} %></h1>
					<% else %> 
							<h1><%= link_to image_tag(">_arrow.png", :alt => "Banner"), {:controller => "play", :action => "question", :game => @game.id, :round => @round.id, :counter => (@counter.to_i() + 1)} %> </h1>
					<% end %> 
			</div>


			<div  class="content main">
				<dix id="ques"> 
					   Question: 
					<%=@question.questiontext %> 
				</dix>
				<div id="answ"> 
					<br/> 
				
					Answer: <%=@question.answertext %> 
					<br/> 
					<br/>

				</div>

				<div id="points">
					Correct: +<%=@question.pointval%> 
					<br/> 
					<% if @question.partialanswer != "" %> 
						For partial credit: 
						<br/><%= @question.partialanswer %> +<%= @question.partialpoints%>
					<%end%>
				</div>
						
		
</div>

app/views/play/game.html.erb
<div class = "page">
	
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center>Choose a Game</center><br>
	</div> 

	<!-- ***Navigation Bar*** -->
	<center><p>
	<%= link_to rounds_path, class: 'btn btn-nav' do %>
		<i class="glyphicon glyphicon-circle-arrow-left"></i> Rounds
	<% end %>
	<%= link_to new_game_path, class: 'btn btn-new' do %>
		<i class="glyphicon glyphicon-plus"></i> Create Game
	<% end %>
	<%= link_to play_index_path, class: 'btn btn-gray' do %>
		<i class="glyphicon glyphicon-align-justify"></i> Main Menu
	<% end %>
	<%= link_to questions_path , class: 'btn btn-nav' do %>
		<i class="glyphicon glyphicon-circle-arrow-right"></i> Questions
	<% end %>
	</p></center>

	<table class="table table-hover"> 
		<thead bgcolor="#6bbeff">
			<tr>
				<th>No.</th> 
				<th>ID</th>
				<th>Game Title</th>
				<th></th>
			</tr>
		</thead>
		<tbody>	
			<% i = 1 %>
			<% @games.each do |game| %> <!-- RUBYISH -->
				<tr> 
					<td> <%= i %> </td>
					<% i = i.to_i() + 1 %> <!-- Casts the iterator from string to integer, so it can be incremented. -->
					<td>
						<%= game.id %> <!-- Adds numbers to the list of available games. -->
					</td>	
					<td>
						<%= link_to game.name, game_path(game) %>
					</td>
					<td>
						<%= link_to 'Play', {:controller => "play", :action => "start", :game => game.id}, class: 'btn btn-success btn-xs' %>
						
						<%= link_to edit_game_path(game), class: 'btn btn-gray btn-xs' do %>
							<i class="glyphicon glyphicon-pencil"></i> Edit
						<% end %>

						<%= link_to game_path(game),
			             		method: :delete,
			              		data: { confirm: 'Are you sure you want to destroy this game?' }, class: 'btn btn-gray btn-xs' do %>
			              		  <i class="glyphicon glyphicon-remove"></i> Delete
							<% end %>
		          	</td>
				</tr>
		<% end %> 
		</tbody>
	</table>
</div>

app/views/play/index.html.erb
<center><%= image_tag("TABlueStars.jpg", :alt => "Banner") %></center>

<div class="page">

<%= link_to 'View Question Repository', questions_path, class: 'btn btn-active_blue btn-lg btn-block' %><br>
<%= link_to 'View Existing Rounds', rounds_path , class: 'btn btn-active_purple btn-lg btn-block' %><br>
<%= link_to 'Select a Game', play_game_path, class: 'btn btn-active_green btn-lg btn-block' %>

</div>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

<!-- Navigation Bar	-->
<center>
<p>
    <%= link_to questions_path, class: 'btn btn-nav' do %>
      <i class="glyphicon glyphicon-circle-arrow-up"></i> Question Repository
    <% end %>


	<%= if @question.round then link_to round_path(@question.round), class: 'btn btn-nav' do %>
			<i class="glyphicon glyphicon-circle-arrow-up"></i> Associated Round
		<% end %>
	<% end %>


</p>
</center>

	<div class = "text">
		<%= f.label :questiontext, "Question" %><br/>
	</div>
		<%= f.text_area :questiontext %><br/>

	<div class = "text">
		<%= f.label :answertext, "Answer" %><br/>
	</div>
		<%= f.text_area :answertext %><br/>

	<div class = "text">
		<%= f.label :partialanswer, "Partial Answer" %><br/>
	</div>
		<%= f.text_area :partialanswer %><br/>

	<div class = "text">
		<%= f.label :difficulty, "Difficulty" %><br/>
	</div>
		<%= f.text_field :difficulty %><br/>

	<div class = "text">
		<%= f.label :pointval, "Points" %><br/>
	</div>
		<%= f.text_field :pointval %><br/>

	<div class = "text">
		<%= f.label :partialpoints, "Partial Points" %><br/>
	</div>
		<%= f.text_field :partialpoints %><br/>

	<div class = "text">
		<%= f.label :notes, "Notes" %><br/>
	</div>
		<%= f.text_area :notes %><br/>

		<br><%= f.submit class: 'btn btn-sm btn-success'%>

<% end %> 

app/views/questions/edit.html.erb
<div class = "page">
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center><h2>Edit Question</h2></center>
	</div> 

	<%= render 'form' %> 

</div>

app/views/questions/index.html.erb
<div class = "page">
	
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center>All Questions</center><br>
	</div> 
	
	<center>
	<p>
  		<%= link_to play_game_path, class: 'btn btn-nav'  do%>
			<i class="glyphicon glyphicon-circle-arrow-left"></i> Games
		<% end %>
		<%= link_to new_question_path, class: 'btn btn-new' do %>
			<i class="glyphicon glyphicon-plus"></i> Add Question
		<% end %>
		<%= link_to play_index_path, class: 'btn btn-gray' do %>
			<i class="glyphicon glyphicon-align-justify"></i> Main Menu
		<% end %>
		<%= link_to rounds_path, class: 'btn btn-nav btn-raised' do %>
			<i class="glyphicon glyphicon-circle-arrow-right"></i> Rounds 
		<% end %>
		
	</p>
	</center>

	<table class="table table-hover"> 
		<thead bgcolor="#6bbeff">
			<tr> 
				<th>No.</th> 
				<th>ID</th>
				<th></th>
				<th>Question</th>
				<th>Answer</th>
				<th>Partial Answer</th>
				<th>Point Value</th>
				<th>Partial Points</th>
			</tr>
		</thead>
		<tbody>
			<% i = 1 %>
			 <% @questions.each do |ques| %>
					<tr>
						<td> <%= i %> </td>
						<% i = i.to_i() + 1 %> <!-- Casts the iterator from string to integer, so it can be incremented. -->
						<td><%= ques.id %></td> <!-- This line adds question ids to the question index. -->
						<td>
							<%= link_to edit_question_path(ques) , class: 'btn btn-edit btn-xs' do %>
								<i class="glyphicon glyphicon-pencil"></i> Edit
							<% end %>
							<%= link_to ques,
		            		  method: :delete,
		            		  data: { confirm: 'Are you sure you want to destroy this question?' }, class: 'btn btn-gray btn-xs' do %>
		            		    <i class="glyphicon glyphicon-remove"></i> Delete
							<% end %>
		          		</td>
						<td> <%= link_to ques.questiontext, ques %> </td>
						<td> <%= ques.answertext %> </td> 
						<td> <%= ques.partialanswer %> </td> 
						<td> <%= ques.pointval %> </td> 
						<td> <%= ques.partialpoints %> </td> 
						
					</tr>
			<% end %>
		</tbody> 
	</table>

</div>

app/views/questions/new.html.erb
<div class = "page">
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center><h2>New Question</h2></center>
	</div> 

	<%= render 'form' %> 

</div>

app/views/questions/show.html.erb
<div class="page">

<%= image_tag("TABanner3.jpg", :alt => "Banner") %>

<!-- Navigation Bar -->
<center>
  <p>
    <%= link_to questions_path, class: 'btn btn-nav' do %>
      <i class="glyphicon glyphicon-circle-arrow-up"></i> Question Repository
    <% end %>

    <%= if @question.round
    link_to 'View Associated Round', round_path(@question.round), class: 'btn btn-nav' 
    end %> <!-- This button needs updating. -->
   
    <%= link_to edit_question_path, class: 'btn btn-gray' do %>
      <i class="glyphicon glyphicon-pencil"></i> Edit
    <% end %>
   
    <%= link_to question_path(@question),
                  method: :delete,
                  data: { confirm: 'Are you sure you want to destroy this question?' } , class: 'btn btn-gray' do %>
      <i class="glyphicon glyphicon-remove"></i> Delete
    <% end %>
  </p>
</center>

<table>
  <tbody>
    
    <td>

      <div class = "heading">
        <strong><h3>Question:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.questiontext %>
      </div>
  

      <div class = "heading">
        <strong><h3>Answer:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.answertext %>
      </div>
    </td>

    <td>
      <div class = "heading">
        <strong><h3>Partial Answer:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.partialanswer %>
      </div>

      <div class = "heading">
        <strong><h3>Notes:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.notes %>
      </div>
    </td>

    <td>
      <div class = "heading">
        <strong><h3>Point Value:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.pointval %>
      </div>
  

      <div class = "heading">
        <strong><h3>Partial Points:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.partialpoints %>
      </div>
    </td>

    <td>
      <div class = "heading">
        <strong><h3>Difficulty:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.difficulty %>
      </div>

      <div class = "heading">
        <strong><h3>ID:</h3></strong>
      </div>
      <div class = "text">
        <%= @question.id %>
      </div>
    
    </td>

  </tbody>
<table>

</div>

app/views/rounds/_form.html.erb
<!-- This nested form includes a grid structure, to make it more user friendly.
As yet, it does not dynamically move to fit the screen, at the mobile level, however. Desktop functionality seems okay at that level, though. -->

<%= nested_form_for @round do |f| %> 

<!-- Navigation Bar -->
<center>
	<p>
		<br><%= link_to rounds_path, class: 'btn btn-sm btn-nav' do %>
			<i class="glyphicon glyphicon-circle-arrow-up"></i> Rounds
    	<% end %><br>

		<%= if @round.game then link_to game_path(@round.game), class: 'btn btn-nav' do %>
			<i class="glyphicon glyphicon-circle-arrow-up"></i> Associated Game
		<% end %>
	<% end %><!-- This button contingency may be removed, as edit question may be left as the checkboxes only, once the option is worked out. -->
	</p>
</center>

<table class = "table">
	<thead>
		<p> 
		<div class = "heading">	
			<h2><%= f.label :title %></h2>
		</div>
		<%= f.text_area :title %> 
		</p>
	</thead>

	<tbody>
		<div id="main-container" class="container-fluid">
			<div class = "row">
				<div id="main content" class="col-md-2">

					<div class = "heading">
						<H3> Question 1 </H3>
					</div>
						<%= f.fields_for :questions do |builder| %> 
								
									<%= render "question_fields", :f => builder %>
									
						<% end %>
					<div class = "heading">
						<H3> Question 2 </H3>
					</div>

						<%= f.fields_for :questions do |builder| %> 
								
							<%= render "question_fields", :f => builder %>
						
						<% end %>

				</div>
				<div id="main content" class="col-md-2">
					<div class = "row"></div>
						
					<div class = "heading">
						<H3> Question 3 </H3>
					</div>
							<%= f.fields_for :questions do |builder| %> 
								
							<%= render "question_fields", :f => builder %>
									
						<% end %>
					<div class = "heading">
						<H3> Question 4 </H3>
					</div>
							<%= f.fields_for :questions do |builder| %> 
								
							<%= render "question_fields", :f => builder %>
									
						<% end %>
	
				</div>
				<div id="main content" class="col-md-2">
					<div class = "row"></div>

					<div class = "heading">
						<H3> Question 5 </H3>
					</div>
							<%= f.fields_for :questions do |builder| %> 
								
							<%= render "question_fields", :f => builder %>
									
						<% end %>

					<div class = "heading">
						<H3> Question 6 </H3>
					</div>
							<%= f.fields_for :questions do |builder| %> 
								
							<%= render "question_fields", :f => builder %>
									
						<% end %>

				</div>
				<div id="main content" class="col-md-2">
					<div class = "row"></div>
						
					<div class = "heading">
						<H3> Question 7 </H3>
					</div>
							<%= f.fields_for :questions do |builder| %> 
								
							<%= render "question_fields", :f => builder %>
									
						<% end %>

				</div>
				<div id="sidebar" class="col-md-2">

					<br><br><br><%= f.submit class: 'btn btn-sm btn-success' %><br>

					<% end %> 

		
				</div>

				</div>
		      </div>
		    </div>
	</tbody>
</table>

app/views/rounds/_form2.html.erb
<%= form_for @round do |f| %>

<!-- Navigation Bar -->

<center>
	<p>
		<%= link_to rounds_path, class: 'btn btn-nav' do  %>
		      <i class="glyphicon glyphicon-circle-arrow-up"></i> Rounds
		<% end %>

	<%= if @round.game then link_to game_path(@round.game), class: 'btn btn-nav' do %>
			<i class="glyphicon glyphicon-circle-arrow-up"></i> Associated Game
		<% end %>
	<% end %>
	<br>
	</p>
</center>

	<p> 
		<div class = "heading">
			<h3><%= f.label :title %></h3>
		</div>
		<%= f.text_area :title %> 
	</p>

	<p> 
		<div class = "text">
			<h3><label>Questions Available:</label></h3>


				<br><%= hidden_field_tag "round[round_ids][]", nil %>
				<% Question.all.sort_by{|question| question.questiontext}.each do |question| %> 				
				<%= check_box_tag "round[question_ids][]", question.id, 
				@round.questions.include?(question), id: dom_id(question)%>
				<%= label_tag dom_id(question), question.questiontext%></br>
					
				<% end %>

				<br/>
		</div>
	</p>

<%= f.submit class: "btn btn-success btn-sm" %>

<% end %> 

<br>

app/views/rounds/index.html.erb
<div class = "page">
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center>All Rounds</center><br>
	</div> 

<!-- ***Navigation Bar*** -->
<center>
<p>
	<%= link_to questions_path, class: 'btn btn-nav' do %>
		<i class="glyphicon glyphicon-circle-arrow-left"></i> Questions 
	<% end %>
	<%= link_to new_round_path, class: 'btn btn-new' do %>
		<i class="glyphicon glyphicon-plus"></i> Create Round
	<% end %>
	<%= link_to play_index_path, class: 'btn btn-gray' do %>
		<i class="glyphicon glyphicon-align-justify"></i> Main Menu
	<% end %>
	<%= link_to play_game_path, class: 'btn btn-nav' do %>
		<i class="glyphicon glyphicon-circle-arrow-right"></i> Games
	<% end %>
</p>
</center>

<table class="table table-hover"> 
	<thead bgcolor="#6bbeff">
		<tr>
			<th>No.</th> 
			<th>ID</th> 
			<th></th>
			<th>Round</th>
		</tr>
	</thead>
	<tbody>
		<% i = 1 %>
		<% @rounds.each do |rnd| %> 
			<tr> 
				<td> <%= i %> </td>
				<% i = i.to_i() + 1 %> <!-- Casts the iterator from string to integer, so it can be incremented. -->
				<td> <%= rnd.id %> </td> <!-- adds round numbers to the index -->
				<td>
					<%= link_to edit_round_path(rnd), class: 'btn btn-gray btn-xs' do %>
						<i class="glyphicon glyphicon-pencil"></i> Edit
					<% end %>

					<%= link_to rnd,
            		  method: :delete,
            		  data: { confirm: 'Are you sure you want to destroy this round?' }, class: 'btn btn-gray btn-xs' do %>
            		  <i class="glyphicon glyphicon-remove"></i> Delete
					<% end %>
				</td>
				<td>
				<%= link_to rnd.title, rnd %> <!-- This line needs syntax that makes the links go somewhere useful. -->
				</td>
			</tr>
		<% end %> 
	</tbody>
</table>
</div>

app/views/rounds/show.html.erb
  <!-- <strong>Round:</strong> -->
<div class="page">
	<div class="heading">
	<%= image_tag("TABanner3.jpg", :alt => "Banner") %>
	<center><h2><%= @round.title%></h2></center>
	<br>
	</div> 

<!-- <H3><%= @round.title %></H3> -->

<!-- Navigation Bar -->
<center>
<p>
<%= link_to rounds_path , class: 'btn btn-nav' do %>
	<i class="glyphicon glyphicon-circle-arrow-up"></i> Rounds
<% end %>

<%= if @round.game then link_to game_path(@round.game), class: 'btn btn-nav' do %>
			<i class="glyphicon glyphicon-circle-arrow-up"></i> Associated Game
		<% end %>
	<% end %>
<!-- The above link needs a condition for questions which are not yet associated with a round. -->
<%= link_to edit_round_path , class: 'btn btn-gray' do %>
   <i class="glyphicon glyphicon-pencil"></i> Edit
<% end %>

<%= link_to round_path(@round),
              method: :delete,
              data: { confirm: 'Are you sure you want to destroy this round?' } , class: 'btn btn-gray' do %>
          				<i class="glyphicon glyphicon-remove"></i> Delete
  					<% end %>
</p>
</center>

<table class="table table-hover">
	<thead bgcolor="#6bbeff">
		<tr>
			<th>No.</th>
			<th>ID</th>
			<th></th>
			<th>Question</th>
			<th>Answer</th>
			<th>Partial Answer</th>
			<th>Point Value</th>
			<th>Partial Points</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<% i = 1 %>
			<% @round.questions.each do |ques| %> <!-- Not sure if this is great syntax... -->
					<td> <%= i %> </td>
					<% i = i.to_i() + 1 %> <!-- Casts the iterator from string to integer, so it can be incremented. -->
					<td> <%= ques.id %> </td>
						<td> 
						<%= link_to edit_question_path(ques), class: 'btn btn-gray btn-xs' do %>
						  	<i class="glyphicon glyphicon-pencil"></i> Edit
						<% end %>
						<%= link_to question_path(ques),
				              method: :delete,
				              data: { confirm: 'Are you sure you want to destroy this question?' } , class: 'btn btn-gray btn-xs' do %>
				             <i class="glyphicon glyphicon-remove"></i> Delete
						<% end %>
					</td>
					<td> <%= link_to ques.questiontext, ques %> </td>
					<td> <%= ques.answertext %></td>
					<td> <%= ques.partialanswer %> </td> 
					<td> <%= ques.pointval %> </td> 
					<td> <%= ques.partialpoints %> </td> 
		</tr>
		<% end %>
	</tbody>
</table>

</div>